### ISSUE TITLE
[Batman] Vi skal kunne understøtte proces typen beregninger i CIM XML og CIM JSON

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/opengeh-edi#20]
Som en aktør har jeg behov for at kunne modtage beskeder som indeholder procestypen "beregninger"

Denne feature omhandler at understøtte den nye procestype i frontenden. Som en ENDK bruger skal man kunne vælge procestypen beregninger i frontenden i forbindelse med start batch. Denne information skal kunne indgå i den udsendte besked til aktøren.

**Acceptance criteria**

- [x] En aktør kan modtage beskeder i CIM JSON og CIM XML som indeholder procestypen "beregninger"

**BEMÆRK** Der er en afhængighed til wholesale som først skal gøre det muligt at vælge procestypen og understøtte at informationen er tilgængelig for EDI. 

**Estimat**
½-1 sprint

**Comment by mogensjuul** [comment]
Enten aggregeringer D03 eller balancefiksering D04 ?
