### ISSUE TITLE
Lav en acceptance test på forespørgsel på anmodninger. 

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/opengeh-edi#30]
Som en del af vores løsning vil vi implementere en acceptance test der tester anmodninger. 
Vi vil teste det følgende scenarie: 

Når en forespørgsel på anmodning er modtaget så dannes en respons til anmodningen som aktøren kan peeke. 

Vi er ikke interreseret i at validere om indholdet er korrekt, da vi ikke kan vide om det data vi har modtaget er korrekt, vi sender bare svaret videre. 

- [ ] Vi har en kørende acceptance test på anmodnings forespørgsler der tester at når en anmodning modtages så dannes en respons til anmodningen.

**Comment by lasrinnil** [comment]
The next step would be to decide on an experiment to run the acceptance tests on. Then go forth with implementing the required test suite to accommodate it.
