### ISSUE TITLE
[BUG] Hvis attributten energySupplier_MarketParticipant ikke findes i XML anmodningen findes ingen data

### ISSUE THREAD

**Issue by RSIEnerginet** [Energinet-DataHub/opengeh-edi#494]
Laver samme anmodning i XML og JSON og i begge tilfælde mangler attributten energySupplier_MarketParticipant i anmodiningen.

Miljø: T-001

I XML anmodningen bliver feltet i databasen= tom, og dermed kommer der ikke data. 
Linje 1=JSON anmodning
Linje 2=XML anmodning

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjNYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f73c7833933e84e54cea589d60a9b86716753974/image.png)

**Comment by RasmusGraabaek** [comment]
XLM og json fortolker manglende attributter forskelligt. Hvis en attribut ikke er angivet ved XML, så får man en tom string, hvor JSON givet "null"
Har lavet en rettelse som fikser det for både el leverandør og balance ansvarlig
