### ISSUE TITLE
[?BUG?] Som Netvirksomhed kan jeg ikke anmode om Produktion pr. netområde (E18) uden at angive målepunkt (netområde?)

### ISSUE THREAD

**Issue by RSIEnerginet** [Energinet-DataHub/opengeh-edi#498]
Som Netvirksomhed kan jeg ikke anmode om Produktion pr. netområde (E18) uden at angive målepunkt. Det skal man iflg. Odgaard kunne. 

Som Netvirksomhed 
Har jeg behov for at anmode om  data for produktion pr. netområde for flere netområder
Så jeg får en samlet oversigt over alle netområder i den angivne periode.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWJlIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--855fbe412787513d03b7f1f8bfc9cb1d60f2bc76/image.png)

**Comment by Christian-Meyer** [comment]
Tror det skal være netområde. Fordi man skal angive E18 hvis man vil have produktion.

**Comment by RasmusGraabaek** [comment]
Denne bliver løst af team-mosaic #17
Så lukker den
