### ISSUE TITLE
[BUG] EBiX peek af FLEX forbrug pr. netområde (E17 E02) står der en forkert værdi i SettlementMethod

### ISSUE THREAD

**Issue by RSIEnerginet** [Energinet-DataHub/opengeh-edi#520]
Som netvirksomhed laver jeg en anmodning i JSON om FLEX forbrug pr. netområde (E17 E02)

Når jeg peeker beskeden i eBix efterfølgende får jeg dette:

<ns0:DetailMeasurementMeteringPointCharacteristic>
<ns0:TypeOfMeteringPoint listAgencyIdentifier="260">E17</ns0:TypeOfMeteringPoint>
**<ns0:SettlementMethod schemeAgencyIdentifier="260">NonProfiled</ns0:SettlementMethod>**
</ns0:DetailMeasurementMeteringPointCharacteristic>

I settlementMethod havde jeg forventet der stod E02

**Comment by RasmusGraabaek** [comment]
test: https://github.com/Energinet-DataHub/opengeh-edi/blob/main/source/Tests/Infrastructure/OutgoingMessages/AggregationResult/AggregationResultDocumentWriterTests.cs

**Comment by johoffma** [comment]
@RasmusGraabaek Du bør lige lave en lille justering i den bugfix du har lavet, da du benytter CimCode.Of. Du skal benytte EbixCode.Of i stedet for.

**Comment by RasmusGraabaek** [comment]
Har rettet det, mange tak :)

**Comment by RSIEnerginet** [comment]
Testet:
Netleverandør:
E17, E17-D01, E17-E02, E18 og E20 sammenholdt med dataudtræk fra databricks. 
Elleverandør: 
E18, E17-D01, E17-E02 sammenholdt med dataudtræk fra databricks. 
Balanceansvarlig: 
Bliver testet når jeg skal teste validering af anmodningerne.

Negativ responce
